name: Linux

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: Build debug ninja
#      env:
#        CFLAGS: -fstack-protector-all -fsanitize=address
#        CXXFLAGS: -fstack-protector-all -fsanitize=address
      run: |
        cmake -DCMAKE_BUILD_TYPE=Debug -B debug-build
        cmake --build debug-build --parallel --config Debug

    - name: Test debug ninja
      run: ./ninja_test
      working-directory: debug-build

    - name: Build release ninja
      shell: bash
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -B release-build
        cmake --build release-build --parallel --config Release
        strip release-build/ninja

    - name: Test release ninja
      run: ./ninja_test
      working-directory: release-build

  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pytest ninja-build

    - name: Configure (GCC)
      run: cmake -Bbuild-gcc -DCMAKE_BUILD_TYPE=Debug -G'Ninja Multi-Config'

    - name: Build (GCC, Debug)
      run: cmake --build build-gcc --config Debug
    - name: Unit tests (GCC, Debug)
      run: ./build-gcc/Debug/ninja_test
    - name: Python tests (GCC, Debug)
      run: pytest-3 --color=yes ../..
      working-directory: build-gcc/Debug

    - name: Build (GCC, Release)
      run: cmake --build build-gcc --config Release
    - name: Unit tests (GCC, Release)
      run: ./build-gcc/Release/ninja_test
    - name: Python tests (GCC, Release)
      run: pytest-3 --color=yes ../..
      working-directory: build-gcc/Release

    - name: Configure (Clang)
      run: CC=clang CXX=clang++ cmake -Bbuild-clang -DCMAKE_BUILD_TYPE=Debug -G'Ninja Multi-Config' -DCMAKE_EXPORT_COMPILE_COMMANDS=1

    - name: Build (Clang, Debug)
      run: cmake --build build-clang --config Debug
    - name: Unit tests (Clang, Debug)
      run: ./build-clang/Debug/ninja_test
    - name: Python tests (Clang, Debug)
      run: pytest-3 --color=yes ../..
      working-directory: build-clang/Debug

    - name: Build (Clang, Release)
      run: cmake --build build-clang --config Release
    - name: Unit tests (Clang, Release)
      run: ./build-clang/Release/ninja_test
    - name: Python tests (Clang, Release)
      run: pytest-3 --color=yes ../..
      working-directory: build-clang/Release

#     - name: clang-tidy
#       run: /usr/lib/llvm-10/share/clang/run-clang-tidy.py -header-filter=src
#       working-directory: build-clang
