name: macOS

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2

    - name: Install re2c
      run: brew install re2c

    - name: Build ninja
      run: |
        cmake -Bbuild
        cmake --build build --config Release

    - name: Test ninja
      run: ctest -C Release -vv
      working-directory: build
